server:
  port: 8888
  max-http-header-size: 2048576
  tomcat.max-http-post-size: 1048576
spring:
  profiles:
    active: demo
  application:
    name: retail
    admin:
      enabled: true
  jmx:
    default-domain: retail
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/retail_management
    name: corporate
    username: postgres
    password: postgres
    hikari:
      max-pool-size: 100
      minimum-idle: 8
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob.non_contextual_creation: true
security:
  basic:
    enabled: false
logging:
  file:
    max-size: 10mb
    max-history: 30
  path: logs
async:
  corePoolSize: 15
  maxPoolSize: 50
  queueCapacity: 10000